### ISSUE TITLE
It's not clear how to contribute.

### ISSUE THREAD

**Issue by EvanCarroll** [FlyBase/chado#1]
I want to help with the Chado schema. How go about suggesting modifications? You have 78,665,953 md5s in your feature table being stored as character(32). That's 36 bytes to store *each* one. They're being stored as varlena. You can save space on disk, and tons of space in ram by storing them as UUID instead.

Moreover, on insertion 

    ('now'::text)::timestamp(6) with time zone

is guaranteed to be slow. Just use `now()`. You should also strongly consider repacking your tables (greatly reducing the size on disk).

**Comment by EvanCarroll** [comment]
You should dump the schema-only with `pg_dump` into the repo, and accept schema-modifications as patches, and stage them on a development db.

**Comment by EvanCarroll** [comment]
Your key configuration is also *highly* redundant.

    TABLE "library_feature" CONSTRAINT "library_feature_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    TABLE "strain_feature" CONSTRAINT "strain_feature_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED

    TABLE "analysisfeature" CONSTRAINT "analysisfeature_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIALLY 
DEFERRED
    TABLE "cell_line_feature" CONSTRAINT "cell_line_feature_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIA
LLY DEFERRED
    TABLE "feature_cvterm" CONSTRAINT "feature_cvterm_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIALLY DE
FERRED
    TABLE "feature_dbxref" CONSTRAINT "feature_dbxref_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INITIALLY DE
FERRED
    TABLE "feature_expression" CONSTRAINT "feature_expression_feature_id_fkey" FOREIGN KEY (feature_id) REFERENCES feature(feature_id) ON DELETE CASCADE DEFERRABLE INIT
IALLY DEFERRED

You realize these are all the same? You've got tons of wasted indexes here...

**Comment by EvanCarroll** [comment]
Some of the redundant keys,

    "feature_organism_id_key" UNIQUE CONSTRAINT, btree (organism_id, uniquename, type_id)
    "feature_idx2" btree (organism_id)

That feature_idx2 is totally redundant, that's 1.6 GB alone.

The same thing on `featureloc_idx1` (redundant) 1.9 GB, and on `analysisfeature_idx1` (1.4GB).

**Comment by EvanCarroll** [comment]
You've also got a hack in there with `point` creating `boxrange`
. create two points (9 bytes each) from two ints (18 bytes total) so you can create a ranged index.

You're recreating the wheel. PostgreSQL supports 
`int4range` https://www.postgresql.org/docs/9.5/static/rangetypes.html which is 9 bytes total. Two int4s, and a 1 byte header.

That'll probably save you another 3 GB.

`binloc_boxrange_src` is also a really bad idea. you probably don't need the index it's creating. If you're searching only on a equijoins with `srcfeature_id` and ranges of fmin,fmax you cna totally nuke it as `srcfeature_id` is already indexed with a btree and the pg planner can use a the btree and the gist together. Alternatively you can make a gist index with `(srcfeature_id, int4range(fmin,fmax))` if you're only goal is to save an index lookup (which is likely a bad idea).

**Comment by jogoodma** [comment]
Hi @EvanCarroll ,
This is the FlyBase repo for misc. Chado related tools.  The repo for the schema itself is https://github.com/GMOD/Chado/.
